import { z } from "zod";

// The 12 curated corridors (context/build-plan.md, Phase 1). Each is a road the
// detectors watch as a unit: an event within `bufferM` of the line matches every
// trip node routed along it.
//
// `waypoints` exist only to pin OSRM to the intended road — where a valley has
// one road, start and end are enough. `profile: "bike"` is for unpaved passes
// OSRM's car profile won't route over (it detours hundreds of km instead); the
// bike profile follows tracks but still avoids footpaths. The stored geometry is the routed line in
// corridors.geo.json, regenerated by `npm run catalogue:corridors`.
//
// `seasonRisk` is seed knowledge, not measured data: month windows are the usual
// ones and move year to year. Verify against local sources before the road form
// (Phase 5) starts citing them to travellers.

export const hazard = z.enum([
  "avalanche",
  "snow-closure",
  "ice",
  "landslide",
  "mudflow",
  "rockfall",
  "flood",
  "fog",
]);

export const seasonRiskEntry = z.object({
  hazard,
  months: z.array(z.number().int().min(1).max(12)).min(1),
  severity: z.enum(["low", "moderate", "high"]),
  note: z.string().min(1),
});

export const seasonRisk = z.array(seasonRiskEntry);
export type SeasonRisk = z.infer<typeof seasonRisk>;

type Waypoint = readonly [name: string, lon: number, lat: number];

export type CorridorDef = {
  slug: string;
  name: string;
  waypoints: readonly Waypoint[];
  profile?: "car" | "bike";
  bufferM: number;
  seasonRisk: SeasonRisk;
};

const winter = [12, 1, 2, 3];

export const corridors: readonly CorridorDef[] = [
  {
    slug: "military-road",
    name: "Georgian Military Road (Tbilisi – Stepantsminda – Larsi)",
    waypoints: [
      ["Tbilisi", 44.793, 41.7151],
      ["Ananuri", 44.7036, 42.1636],
      ["Gudauri", 44.4783, 42.4769],
      ["Stepantsminda", 44.644, 42.657],
      ["Larsi", 44.6307, 42.7442],
    ],
    bufferM: 2000,
    seasonRisk: [
      {
        hazard: "avalanche",
        months: [12, 1, 2, 3, 4],
        severity: "high",
        note: "Gudauri – Kobi over the Jvari Pass; closures often last days.",
      },
      {
        hazard: "snow-closure",
        months: [11, 12, 1, 2, 3, 4],
        severity: "high",
        note: "Pass closed to all or to trucks after heavy snowfall.",
      },
      {
        hazard: "mudflow",
        months: [5, 6, 7, 8],
        severity: "moderate",
        note: "Devdoraki and Dariali gorge sections below Stepantsminda.",
      },
    ],
  },
  {
    slug: "gombori-pass",
    name: "Gombori Pass (Tbilisi – Telavi)",
    waypoints: [
      ["Tbilisi", 44.793, 41.7151],
      ["Telavi", 45.4731, 41.9198],
    ],
    bufferM: 1500,
    seasonRisk: [
      {
        hazard: "ice",
        months: winter,
        severity: "moderate",
        note: "Hairpins either side of the pass; traffic reroutes via Sagarejo.",
      },
      {
        hazard: "fog",
        months: [10, 11, 12, 1, 2, 3],
        severity: "low",
        note: "Low cloud on the forested summit section.",
      },
    ],
  },
  {
    slug: "kakheti-highway",
    name: "Kakheti Highway (Tbilisi – Sagarejo – Sighnaghi)",
    waypoints: [
      ["Tbilisi", 44.793, 41.7151],
      ["Sagarejo", 45.3311, 41.734],
      ["Sighnaghi", 45.9217, 41.6197],
    ],
    bufferM: 1500,
    seasonRisk: [
      {
        hazard: "ice",
        months: [12, 1, 2],
        severity: "low",
        note: "Climb up to Sighnaghi after freezing nights.",
      },
    ],
  },
  {
    slug: "east-west-highway",
    name: "East–West Highway (Tbilisi – Rikoti – Kutaisi)",
    waypoints: [
      ["Tbilisi", 44.793, 41.7151],
      ["Gori", 44.1158, 41.9842],
      ["Khashuri", 43.5992, 41.9947],
      ["Zestaponi", 43.052, 42.11],
      ["Kutaisi", 42.6946, 42.2679],
    ],
    bufferM: 1500,
    seasonRisk: [
      {
        hazard: "snow-closure",
        months: winter,
        severity: "moderate",
        note: "Rikoti Pass section between Khashuri and Zestaponi.",
      },
      {
        hazard: "fog",
        months: [11, 12, 1, 2, 3],
        severity: "moderate",
        note: "Rikoti Pass and the Shida Kartli plain.",
      },
    ],
  },
  {
    slug: "kutaisi-batumi",
    name: "Kutaisi – Batumi",
    waypoints: [
      ["Kutaisi", 42.6946, 42.2679],
      ["Samtredia", 42.338, 42.154],
      ["Kobuleti", 41.7792, 41.8214],
      ["Batumi", 41.6367, 41.6168],
    ],
    bufferM: 1500,
    seasonRisk: [
      {
        hazard: "flood",
        months: [9, 10, 11],
        severity: "moderate",
        note: "Autumn downpours on the Adjara coast; low sections near Kobuleti.",
      },
    ],
  },
  {
    slug: "borjomi-bakuriani",
    name: "Borjomi Gorge (Khashuri – Borjomi – Bakuriani)",
    waypoints: [
      ["Khashuri", 43.5992, 41.9947],
      ["Borjomi", 43.379, 41.839],
      ["Bakuriani", 43.532, 41.75],
    ],
    bufferM: 1500,
    seasonRisk: [
      {
        hazard: "snow-closure",
        months: winter,
        severity: "moderate",
        note: "Borjomi – Bakuriani climb; chains sometimes required.",
      },
      {
        hazard: "rockfall",
        months: [3, 4, 5],
        severity: "moderate",
        note: "Mtkvari gorge walls during thaw.",
      },
    ],
  },
  {
    slug: "vardzia",
    name: "Borjomi – Akhaltsikhe – Vardzia",
    waypoints: [
      ["Borjomi", 43.379, 41.839],
      ["Akhaltsikhe", 43.4861, 41.4056],
      ["Vardzia", 43.284, 41.381],
    ],
    bufferM: 1500,
    seasonRisk: [
      {
        hazard: "rockfall",
        months: [3, 4, 5],
        severity: "moderate",
        note: "Mtkvari canyon below Khertvisi and the Vardzia approach.",
      },
      {
        hazard: "ice",
        months: winter,
        severity: "moderate",
        note: "Javakheti plateau; among the coldest roads in the country.",
      },
    ],
  },
  {
    slug: "svaneti-road",
    name: "Enguri Gorge (Zugdidi – Mestia)",
    waypoints: [
      ["Zugdidi", 41.8709, 42.5088],
      ["Mestia", 42.7277, 43.0459],
    ],
    bufferM: 2000,
    seasonRisk: [
      {
        hazard: "rockfall",
        months: [4, 5, 6],
        severity: "high",
        note: "Enguri gorge above the dam; debris closes a lane for hours.",
      },
      {
        hazard: "avalanche",
        months: winter,
        severity: "high",
        note: "Khaishi – Mestia sections.",
      },
      {
        hazard: "landslide",
        months: [9, 10],
        severity: "moderate",
        note: "Autumn rain on already-loose slopes.",
      },
    ],
  },
  {
    slug: "mestia-ushguli",
    name: "Mestia – Ushguli",
    waypoints: [
      ["Mestia", 42.7277, 43.0459],
      ["Ushguli", 43.012, 42.917],
    ],
    bufferM: 2000,
    seasonRisk: [
      {
        hazard: "snow-closure",
        months: [11, 12, 1, 2, 3, 4],
        severity: "high",
        note: "Upper section can be cut for days; Ushguli is then unreachable.",
      },
      {
        hazard: "mudflow",
        months: [4, 5, 6],
        severity: "high",
        note: "Unpaved stretches wash out during snowmelt.",
      },
    ],
  },
  {
    slug: "zagari-pass",
    name: "Lentekhi – Zagari Pass – Ushguli",
    waypoints: [
      ["Lentekhi", 42.726, 42.788],
      ["Ushguli", 43.012, 42.917],
    ],
    profile: "bike",
    bufferM: 2000,
    seasonRisk: [
      {
        hazard: "snow-closure",
        months: [10, 11, 12, 1, 2, 3, 4, 5, 6],
        severity: "high",
        note: "Zagari Pass is typically passable only July – September, 4x4 only.",
      },
      {
        hazard: "mudflow",
        months: [6, 7, 8],
        severity: "high",
        note: "River crossings and washouts above Lentekhi.",
      },
    ],
  },
  {
    slug: "tusheti",
    name: "Akhmeta – Abano Pass – Omalo",
    waypoints: [
      ["Akhmeta", 45.207, 42.031],
      ["Omalo", 45.635, 42.374],
    ],
    bufferM: 2000,
    seasonRisk: [
      {
        hazard: "snow-closure",
        months: [10, 11, 12, 1, 2, 3, 4, 5],
        severity: "high",
        note: "Abano Pass (2,826 m) usually opens in June and closes in early October.",
      },
      {
        hazard: "landslide",
        months: [6, 7, 8, 9],
        severity: "high",
        note: "Unpaved single-track; rain closes it with no detour.",
      },
    ],
  },
  {
    slug: "goderdzi-pass",
    name: "Batumi – Khulo – Goderdzi Pass – Akhaltsikhe",
    waypoints: [
      ["Batumi", 41.6367, 41.6168],
      ["Keda", 41.94, 41.6],
      ["Khulo", 42.315, 41.644],
      ["Adigeni", 42.702, 41.684],
      ["Akhaltsikhe", 43.4861, 41.4056],
    ],
    bufferM: 2000,
    seasonRisk: [
      {
        hazard: "snow-closure",
        months: [12, 1, 2, 3, 4],
        severity: "high",
        note: "Goderdzi Pass (2,025 m) between Khulo and Adigeni.",
      },
      {
        hazard: "landslide",
        months: [3, 4, 5, 10, 11],
        severity: "moderate",
        note: "Adjara mountain section; heavy rainfall zone.",
      },
    ],
  },
];
